spring:
  datasource:
    username: process.env.MYSQL_USERNAME
    password: process.env.MYSQL_PASSWORD
    url: process.env.MYSQL_URL
    driver-class-name: process.env.MYSQL_DRIVER
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: process.env.MYSQL_HIBERNATE

